if has("gui_macvim")
  " Cmd+T to open Command-T
  macmenu &File.New\ Tab key=<nop>
  nmap <D-t> :CommandT<CR>
  imap <D-t> <Esc>:CommandT<CR>

  " Cmd+R to flush Command-T cache
  nmap <D-r> :CommandTFlush<CR>
  imap <D-r> <Esc>:CommandTFlush<CR>

  " Cmd+W to close current buffer and close the window if no buffers are left
  macmenu &File.Close key=<nop>
  nmap <D-w> :CommandW<CR>
  imap <D-w> <Esc>:CommandW<CR>

  menu File.Close\ Instance :qa<CR>
  inoremenu File.Close\ Instance :qa<CR>

  set cc=80                                  " Put at line @ column 80
  set guioptions-=T                          " Hide the tool bar
  set guioptions=ce
  "              ||
  "              |+-- use simple dialogs rather than pop-ups
  "              +--- use GUI tabs, not console style tabs

  set guifont=Monaco:h14
endif

" Set column for features
autocmd BufWinEnter *.feature set cc+=11
autocmd BufWinLeave *.feature set cc-=11
