if has('gui_macvim')
  set guifont=Monaco:h14

  " Allow colour to be set on insert cursor
  set guicursor+=i:ver25-iCursor

  " Hide the tool bar
  set guioptions-=T

  " Use simple dialogs rather than pop-ups
  set guioptions=c
endif
