" Misc
set nowrap                                  " I don't always wrap lines...
set linebreak                               " ...but when I do, I wrap whole words.
set t_Co=256                                " Support for xterm with 256 colors (gets overriden in .gvimrc)
set number                                  " Show line numbers
set ruler                                   " Show ruler
set listchars=trail:.,tab:>-,eol:¬          " Change the invisible characters
set noswapfile                              " Don't create annoying *.swp files
set scrolloff=5                             " Start scrolling the file 5 lines before the end of the window
set spelllang=en_au                         " Set default spelling language to English (Australia)
set hidden                                  " Allow hiding buffers with unsaved changes
set wildmenu                                " Make tab completion act more like bash
set wildmode=list:longest                   " Tab complete to longest common string, like bash
set showcmd                                 " Display an incomplete command in the lower right corner
set showmode                                " Show current mode down the bottom
set laststatus=2                            " Always show the status line
set history=1000
set autoread

" Persistent Undo
set undodir=$HOME/.vim/.undo
set undofile
set undolevels=1000
set undoreload=10000

autocmd FileType gitcommit set spell        " Turn on spell check in Git commits.

" FocusLost
autocmd FocusLost * nested :silent! wall    " Save on FocusLost
autocmd FocusLost * call feedkeys("\<C-\>\<C-n>") " Return to normal mode on FocustLost

" Treat dasherised words as whole words in stylesheets
autocmd Filetype css,scss,sass setlocal iskeyword+=-

function! WhatTheSize()
  execute ":!identify % | cut -d' ' -f 3"
endfunction
autocmd BufEnter *.jpg,*.png call WhatTheSize()

" Searching
set hlsearch                                " Highlight searches
set incsearch                               " Highlight search results instantly
set ignorecase                              " Ignore case
set smartcase                               " Override 'ignorecase' option if the search contains upper case characters.

filetype plugin indent on                   " Enable automatic filetype detection, filetype-specific plugins/indentation

" Indentation
set shiftwidth=2                            " Number of spaces to use in each autoindent step
set tabstop=2                               " Two tab spaces
set softtabstop=2                           " Number of spaces to skip or insert when <BS>ing or <Tab>ing
set expandtab                               " Spaces instead of tabs for better cross-editor compatibility
set autoindent                              " Keep the indent when creating a new line
set smarttab                                " Use shiftwidth and softtabstop to insert or delete (on <BS>) blanks
set cindent                                 " Recommended seting for automatic C-style indentation
set autoindent                              " Automatic indentation in non-C files

" Colorscheme
syntax enable
set background=dark
colorscheme jellybeans_custom

" Use % to jump to matching begin/end of blocks as well as brackets/parens
runtime macros/matchit.vim
