alias gb='git branch'
alias gba='git branch -a'
alias gup='gup && say gup done'
alias gcod='gco develop'
alias gcom='gco master'
alias gf='git fetch'
alias gsw='git show --format=fuller'
alias prune='git remote prune origin'
alias garm='git ls-files -dz | xargs -0 git rm'
alias gri='git rebase --interactive'
