# ln -s ~/.dotfiles/zsh/zshrc .zshrc # Setup .zshrc symlink (command must be run from ~/)

# Source my dotfiles
source ~/.dotfiles/config

export ZSH=$HOME/.oh-my-zsh # Path to your oh-my-zsh configuration.
export ZSH_THEME="my" # Set to the name theme to load. Look in ~/.oh-my-zsh/themes/
export CASE_SENSITIVE="true" # Set to this to use case-sensitive completion
# export DISABLE_AUTO_UPDATE="true" # Comment this out to disable weekly auto-update checks
# export DISABLE_LS_COLORS="true" # Uncomment following line if you want to disable colors in ls

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(osx)

if [ -d "$ZSH" ]; then
  source $ZSH/oh-my-zsh.sh
else
  echo "Cloning oh-my-zsh..."
  /usr/bin/env git clone git://github.com/robbyrussell/oh-my-zsh.git "$ZSH"
  source $ZSH/oh-my-zsh.sh
fi

# Customize to your needs...
export PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/X11/bin:/usr/local/mysql/bin

# Ensure that rvm is the last thing sourced in all of your shell profiles, 
# especially PATH are set.
# Otherwise, the values you set be trampled when you switch rubies.
source ~/.dotfiles/shell/rvm.sh