# BASH specific
source $DOTFILES/lib/git_completion
source $DOTFILES/bash/colours

# Binds
bind 'set completion-ignore-case on '
bind 'set bell-style none' # No bell, because it's damn annoying
bind 'set show-all-if-ambiguous On' # this allows you to automatically show completion without double tab-ing

# Sets title of window to be user@host
export PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*} ${PWD}"; echo -ne "\007"'

# Make git colourful
git config --global color.ui auto

# Promt config
# [~ (git_branch)] user@hostname »
# [ GREEN current directory END_GREEN ( YELLOW git branch ) ] user@hostname END_YELLOW »
# The __git_ps1 comes from the ~/.dotfiles/lib/git_completion file
# Default prompt (export PS1="\h:\W \u\$ ")

export PS1="\
[\[$(colour green)\]\W\[$(colour reset)\]]\
\[$(colour light_yellow)\]\$(__git_ps1 \" (%s)\")\
\[$(colour light_yellow)\]\[$(user_hostname)\]\[$(colour reset)\] \
\[$(colour $(prompt_color))\]»\[$(colour reset)\] "